### ISSUE TITLE
Проверка ДЗ 2 СУБД

### ISSUE THREAD

**Issue by konopkin11** [go-park-mail-ru/2024_1_Cyberkotletki#13]

**Comment by konopkin11** [comment]
Почему так мало? 
db.SetConnMaxLifetime(time.Second * 10)

https://www.alexedwards.net/blog/configuring-sqldb читаем

**Comment by konopkin11** [comment]
> // запросs занимают до 1 с, 1 соединение может обработать 1 req/sec или 60 req/min
> 	// 100 соединений может обработать 100 req/sec или 6000 req/min

Точно? У вас сервер потянет 100 асинхронных соединений?

**Comment by konopkin11** [comment]
По поводу миграций на добавление расширений.
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
Нужно быть уверенным, что юзер имеет роль SUPERUSER для добавления расширений. Осознанно сделано, что юзер, под которым приложение ходит в бд, имеет такую роль?

**Comment by konopkin11** [comment]
Пару слов почему Squirrel  защищает вас от SQL Injection?

**Comment by KristinaBu** [comment]
> По поводу миграций на добавление расширений. CREATE EXTENSION IF NOT EXISTS pg_stat_statements; Нужно быть уверенным, что юзер имеет роль SUPERUSER для добавления расширений. Осознанно сделано, что юзер, под которым приложение ходит в бд, имеет такую роль?

Да, в Makefile в корне проекта создается пользователь kinoskop_admin, который имеет роль суперпользователя. Это проверено, все миграции накатываются успешно. 

> Пару слов почему Squirrel защищает вас от SQL Injection?

SQL-инъекции происходят, когда злоумышленник может ввести вредоносный SQL-код в поля ввода формы, который затем используется в SQL-запросе без должной экранировки или параметризации. С помощью Squirrel производится параметризация запроса, устанавливаются типы данных.
Также перед осуществлением запроса производится валидация данных. Например, валидация из internal/entity/user.go используется в internal/usecase/service/user.go перед вызовом функции вставки/редактирования из репозитория

> Почему так мало? db.SetConnMaxLifetime(time.Second * 10)
> 
> https://www.alexedwards.net/blog/configuring-sqldb читаем

Спасибо. Я внесла изменения
