### ISSUE TITLE
Проверка ДЗ1 СУБД

### ISSUE THREAD

**Issue by konopkin11** [go-park-mail-ru/2024_1_Cyberkotletki#8]
ER- диаграмма
1. ER диаграмма крутая 😎 , правда в домашке написано не указывать типы данных, но я уточню это лишняя работа или именно ошибка)
2. У каждой таблицы должен быть первичный ключ. Если смотреть по диаграмме - то, например, у таблицы CONTENT_STATUS нет первичного ключа, а только внешние.
3. На текущий момент не видел миграции, но смею предположить, что email юзера уникален, а значит это потенциальный (альтернативный) ключ, знать в диаграмме лучше его пометить как AK. 
4. Расскажите пж в комментарии для чего нужно поле SALT_PASSWORD
5. to be continued...

Нормализация: 
1. Вы путаете внешние ключи с теорией нормализации. В теории нормализации вы внешние ключи рассматриваете как обычные поля. Например, {CONTENT_ID} -> CONTENT {ID} серьезная ошибка, так как в вашей таблице аудиторий нет атрибута контент.
2. По ощущениям пропущен потенциальный ключ { id контента, id страны }
https://github.com/go-park-mail-ru/2024_1_Cyberkotletki/blob/8c9786f2a68a79d9e02c9c9708678edfd870f1e3/db/normalized/relations.md?plain=1#L59
3. Вам точно нужна таблица Roles? Если да, то name можно сделать уникальным, иначе странная таблица получается. UPD Вижу, что в миграции уникально, но тогда это точно альтернативный ключ
4. чем название отличается от оригинального названия? Если оригинальное название уникально, то это должно быть ключом. 
https://github.com/go-park-mail-ru/2024_1_Cyberkotletki/blob/8c9786f2a68a79d9e02c9c9708678edfd870f1e3/db/normalized/relations.md?plain=1#L244
5. Ни в одной вспомогательной таблице не определен первичный ключ - значит отношение даже не в 1НФ

Миграции
1. ограничение NOT NULL но ON DELETE SET NULL? Такую же ошибку в других таблицах не буду помечать
https://github.com/go-park-mail-ru/2024_1_Cyberkotletki/blob/8c9786f2a68a79d9e02c9c9708678edfd870f1e3/db/migrations/migration_0.sql#L65
2. Некоторые названия таблиц в множественном числе

**Comment by konopkin11** [comment]
UPD уточнил про диаграмму. Типы данных оставьте, получилось круто. Это не ошибка

**Comment by konopkin11** [comment]
UPD
использование TIMESTAMP вместо TIMESTAMPTZ (https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_NOT_IN)
https://github.com/go-park-mail-ru/2024_1_Cyberkotletki/blob/8c9786f2a68a79d9e02c9c9708678edfd870f1e3/db/migrations/migration_0.sql#L68C16-L68C25

**Comment by konopkin11** [comment]
1. временные метки не исправлены на TIMESTAMPTZ
2. В таблицу альтернативные ключи тоже укажите как AK, если ключей несколько, то AK1, AK2, если альтернативный ключ составной то AK1.1, AK1.2, если альтернативный ключ еще и внешний, то через запятую и то и то. (альтернативный ключ это UNIQUE ограничение)
3. форматирование в миграции вообще нечитаемое. Я проверю конечно, но надо что-то с этим придумать. Может ограничения вынести за таблицу?
4. Не нашел в нормализации описания таблицы static - не понимаю для чего она. Если это для внешнего хранилища, то может так и назвать file?
5. Точно нфбк?
<img width="293" alt="image" src="https://github.com/go-park-mail-ru/2024_1_Cyberkotletki/assets/36122361/5ee2d7fe-efad-46d0-a7c5-0171aaf3e8ad">

**Comment by ns-roxer** [comment]
https://github.com/go-park-mail-ru/2024_1_Cyberkotletki/blob/subd/db/migrations/20240330230838_init.sql#L131 - тут явно не хватает уникального ключа

**Comment by ns-roxer** [comment]
person_roles - https://github.com/go-park-mail-ru/2024_1_Cyberkotletki/blob/subd/db/migrations/20240330230838_init.sql#L97 - есть уникальный ключ, но нет primary key - не порядок, было сказано, что явно должен быть обозначен PK.

content_content_type - https://github.com/go-park-mail-ru/2024_1_Cyberkotletki/blob/subd/db/migrations/20240330230838_init.sql#L268 - а тут ни уникального, ни PK, тоже непорядок.
